# Generated by Django 3.2.14 on 2022-07-27 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 27, 22, 46, 37, 981001))),
            ],
        ),
    ]
