# Generated by Django 3.2.14 on 2022-07-28 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinnerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheel',
            name='ending_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheel',
            name='img',
            field=models.ImageField(default='intro.png', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='wheel',
            name='starting_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 23, 1, 1, 788456)),
        ),
    ]
