# Generated by Django 3.2.14 on 2022-07-29 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinnerapp', '0002_auto_20220728_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 30, 0, 41, 28, 324217))),
            ],
        ),
        migrations.AlterField(
            model_name='wheel',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 30, 0, 41, 28, 308596)),
        ),
    ]
